document.addEventListener("DOMContentLoaded",async()=>{
const msg=document.getElementById("admin-message"), u=await NTP.user(); if(!u||!window.ntpSupabase){msg.innerHTML='<div class="notice">Bạn cần đăng nhập và cấu hình Supabase.</div>';return}
const {data:p}=await ntpSupabase.from("profiles").select("*").eq("id",u.id).maybeSingle();if(p?.role!=="admin"){msg.innerHTML='<div class="notice">Tài khoản không có quyền admin.</div>';return}
const tabs=document.querySelectorAll(".tab"), panels={dashboard:dashboard,products:products,orders:orders};
tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove("active"));t.classList.add("active");Object.values(panels).forEach(x=>x.classList.add("hidden"));panels[t.dataset.tab].classList.remove("hidden");load(t.dataset.tab)});
document.getElementById("admin-logout").onclick=async()=>{await ntpSupabase.auth.signOut();location.href="index.html"};
async function load(tab){if(tab==="dashboard"){const [{count:pc},{count:oc}]=await Promise.all([ntpSupabase.from("products").select("*",{count:"exact",head:true}),ntpSupabase.from("orders").select("*",{count:"exact",head:true})]);dashboard.innerHTML=`<div class="stats-grid"><div class="stat-card"><span>Sản phẩm</span><b>${pc||0}</b></div><div class="stat-card"><span>Đơn hàng</span><b>${oc||0}</b></div><div class="stat-card"><span>Vai trò</span><b>ADMIN</b></div></div>`}
if(tab==="products"){const {data}=await ntpSupabase.from("products").select("*").order("created_at",{ascending:false});products.innerHTML=`<div class="admin-form"><h3>Thêm sản phẩm</h3><form id="add-product"><input id="pname" placeholder="Tên sản phẩm" required><input id="pgame" placeholder="Game / nền tảng" required><input id="pprice" type="number" placeholder="Giá" required><select id="pcat"><option value="account">Acc Game</option><option value="service">Cày thuê</option><option value="digital">MXH & Website</option></select><textarea id="pdesc" placeholder="Mô tả"></textarea><button class="btn btn-primary">Thêm</button></form></div><div class="admin-table">${(data||[]).map(x=>`<div class="admin-row"><span>${NTP.esc(x.name)}<small>${NTP.esc(x.game)}</small></span><b>${NTP.money(x.price)}</b><span class="status">${x.is_active?"Hiện":"Ẩn"}</span><button class="mini-btn toggle-product" data-id="${x.id}" data-active="${x.is_active}">${x.is_active?"Ẩn":"Hiện"}</button></div>`).join("")}</div>`;document.getElementById("add-product").onsubmit=async e=>{e.preventDefault();await ntpSupabase.from("products").insert({name:pname.value,game:pgame.value,price:+pprice.value,category:pcat.value,description:pdesc.value,is_active:true,stock:1});load("products")};products.querySelectorAll(".toggle-product").forEach(b=>b.onclick=async()=>{await ntpSupabase.from("products").update({is_active:b.dataset.active!=="true"}).eq("id",b.dataset.id);load("products")})}
if(tab==="orders"){const {data}=await ntpSupabase.from("orders").select("*").order("created_at",{ascending:false});orders.innerHTML=`<div class="admin-table">${(data||[]).map(x=>`<div class="admin-row"><span><b>${NTP.esc(x.order_code)}</b><small>${NTP.esc(x.customer_name||"")}</small></span><b>${NTP.money(x.total_amount)}</b><select class="order-status" data-id="${x.id}">${["pending","paid","processing","completed","cancelled"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}</div>`;orders.querySelectorAll(".order-status").forEach(s=>s.onchange=async()=>{await ntpSupabase.from("orders").update({status:s.value}).eq("id",s.dataset.id)})}}
load("dashboard");
});